[".tmux/plugins/tpm"]
  type = "git-repo"
  url = "https://github.com/tmux-plugins/tpm.git"
[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/AstroNvim/AstroNvim.git"
[".config/nvim".clone]
  args = ["-b", "nightly", "--depth", "1"]
