[".oh-my-zsh"]
  type = "git-repo"
  url = "https://github.com/ohmyzsh/ohmyzsh.git"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
  type = "archive"
  refreshPeriod = "168h"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  include = ["*/*.zsh", "*/.version", "*/.revision-hash", "*/highlighters/**"]
[".oh-my-zsh/custom/themes/powerlevel10k"]
  type = "archive"
  refreshPeriod = "168h"
  url = "https://github.com/romkatv/powerlevel10k/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  exclude = ["**/*.png", "**/*.md"]
[".tmux/plugins/tpm"]
  type = "archive"
  refreshPeriod = "168h"
  url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
  exact = true
  stripComponents = 1
[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/AstroNvim/AstroNvim.git"
[".config/nvim".clone]
  args = ["-b", "v3"]
