return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.bars-and-lines.heirline-mode-text-statusline" },
  { import = "astrocommunity.editing-support.todo-comments-nvim" },
  { import = "astrocommunity.editing-support.nvim-ts-rainbow2" },
  { import = "astrocommunity.editing-support.cutlass-nvim" },
  { import = "astrocommunity.pack.typescript-all-in-one" },
  { import = "astrocommunity.note-taking.obsidian-nvim" },
  { import = "astrocommunity.code-runner.overseer-nvim" },
  { import = "astrocommunity.diagnostics.trouble-nvim" },
  { import = "astrocommunity.lsp.lsp-inlayhints-nvim" },
  { import = "astrocommunity.colorscheme.catppuccin" },
  { import = "astrocommunity.completion.copilot-lua" },
  { import = "astrocommunity.motion.mini-surround" },
  { import = "astrocommunity.startup.fsplash-nvim" },
  { import = "astrocommunity.git.git-blame-nvim" },
  { import = "astrocommunity.motion.nvim-spider" },
  { import = "astrocommunity.motion.vim-matchup" },
  { import = "astrocommunity.utility.noice-nvim" },
  { import = "astrocommunity.motion.flit-nvim" },
  { import = "astrocommunity.motion.mini-move" },
  { import = "astrocommunity.pack.markdown" },
  { import = "astrocommunity.pack.python" },
  { import = "astrocommunity.pack.rust" },
  { import = "astrocommunity.pack.yaml" },
  { import = "astrocommunity.pack.lua" },
  {
    "catppuccin",
    opts = {
      flavour = "mocha",
      transparent_background = true,
      integrations = {
        indent_blankline = { enabled = true, colored_indent_levels = false },
        dap = { enabled = true, enable_ui = true },
        semantic_tokens = true,
        lsp_trouble = true,
        ts_rainbow2 = true,
        treesitter = true,
        telescope = true,
        which_key = true,
        gitsigns = true,
        markdown = true,
        overseer = true,
        neotree = true,
        aerial = true,
        notify = true,
        mason = true,
        noice = true,
        leap = true,
        mini = true,
        cmp = true,
        native_lsp = {
          enabled = true,
          virtual_text = {
            information = { "italic" },
            warnings = { "italic" },
            errors = { "italic" },
            hints = { "italic" },
          },
          underlines = {
            information = { "underline" },
            warnings = { "underline" },
            errors = { "underline" },
            hints = { "underline" },
          },
        },
      },
    },
  },
  {
    "epwalsh/obsidian.nvim",
    opts = {
      dir = "~/Documents/Obsidian\\ Vault",
      completion = { nvim_cmp = true },
      daily_notes = { folder = "daily" },
    },
  },
  {
    "zbirenbaum/copilot.lua",
    opts = {
      suggestion = {
        keymap = {
          accept = "<C-l>",
          next = "<C-;>",
          prev = "<C-'>",
        },
      },
      filetypes = { markdown = true },
    },
  },
}
